### ISSUE TITLE
to do list

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/gtfstools#1]
- [x] remove little `usethis` dependency when saving gtfs_metadata
- [x] implement filtering functions
- [ ] implement `gtfstools_to_tidytransit()`
- [x] implement `set_times_to_seconds()`
- [x] implement `prune_gtfs()`
- [x] reduce `poa_gtfs` after implementing filtering functions
- [x] create vignette
- [x] improve README
- [x] change `merge_gtfs()` and `validate_gtfs()` examples

please add here or comment below any other features you'd like to see

things I really need to check/know might be problematic:

- [ ] need to check if first departure_time/last arrival_time are missing and handle it adequately in `get_trip_duration()
- [x] [Suggests != Depends](https://dirk.eddelbuettel.com/blog/2017/03/22/) - conditionally run tests and examples that depend on `{lwgeom}`

**Comment by dhersz** [comment]
note to self: write tests as you write functions

**Comment by mpadge** [comment]
@dhersz i'm restructing `gtfsrouter` to use lots of your great stuff. There is one function which used to live within my `extract_gtfs()` function which has now been replaced by `gtfsio::import_gtfs()`, and which is still needed, but would maybe be better living here. It is pure C++, and does one of the items listed above:

- [x] implement `set_times_to_seconds()`.

It works just like [these two lines](https://github.com/ATFutures/gtfs-router/blob/cb5e270ce76ff3e81c58415258426b7191cfe38d/R/extract-gtfs.R#L243-L244) - a single line call that is way faster than any R functions to do this. Let me know and i'll happily PR here.

**Comment by rafapereirabr** [comment]
I think this would be a great contribution, @mpadge .

**Comment by mpadge** [comment]
Great! It's currently just an internal function that calls directly to the C++ code, so we'll just need to work out whether you might actually want it as some kind of exported and R-wrapped function? I can get a PR together in the meantime regardless, initially with just the internal C++ code, and we can work out where the two lines of R code go:
``` r
stop_times [, arrival_time := rcpp_time_to_seconds (arrival_time)]
stop_times [, departure_time := rcpp_time_to_seconds (departure_time)]
```

**Comment by dhersz** [comment]
Hi @mpadge. This is so good, many thanks!

Just some backstory behind `set_times_to_seconds()`: I currently use a `string_to_seconds()` functions I wrote based on `tidytransit::hms_to_seconds()` (or something along these lines) to convert the time inside functions that require such conversion, such as [`get_trip_duration()`](https://github.com/ipeaGIT/gtfstools/blob/62f19e01fb9df97d147be2db01ffd5037b84b8dc/R/get_trip_duration.R#L99). Your function is certainly much faster than the one I use right now, so I'll gladly start using it instead.

Now, I wanted to have `set_times_to_seconds()` to save some time when repeatedly calculating the duration of trips, or something like this, because right now `get_trip_duration()` will *always* create two new columns `arrival_time_secs` and `departure_time_secs` via `string_to_seconds()` when making such calculations. Therefore, the purpose of `set_times_to_seconds()` would be to create such columns beforehand, so the user would only need to make this conversion once, instead of every single time they wanted to calculate durations or speeds (hence requiring a check inside `get_trip_duration()` to see if these columns already exist).

Because your function is so much faster than `string_to_seconds()`, which was written purely in R, perhaps `set_times_to_seconds()` as I first thought of it is not as important right now. So to answer your question, I'd keep `rcpp_time_to_seconds()` as a internal function right now and add a wrapper (`set_times_to_seconds()`) later.

**Comment by dhersz** [comment]
Closing this in favor of individual issues.
