### ISSUE TITLE
Hex sticker

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/gtfstools#21]
Revisiting the hex stickers today, I have two suggestions for `gtfstools`:

![gtfs tools hex](https://user-images.githubusercontent.com/7387691/110789074-3dc03a00-824e-11eb-8c6e-b2f3e0d6d01e.png)

**Comment by rafapereirabr** [comment]
I prefer the option on the left, to keep the hex sticker consistent with other packages, `gtfs2gps` and `gtfs2emis`.

On a side note, how about we replace the hammer and wrench with a single wrench to make the logo cleaner?

**Comment by pedro-andrade-inpe** [comment]
I particularly do not like the idea of separating the name of the package in two parts. My suggestion would be something like:

```
gtfstools |
----------|
  <hammer>|
```

**Comment by rafapereirabr** [comment]
I prefer the option on the left. I would just make the black hex thinner.

**Comment by rafapereirabr** [comment]
Have we decided on a Hex sticker ? I personally the option on the left, proposed by Marcus, but I would prefer a thin black border or remove the border completly.

**Comment by mvpsaraiva** [comment]
A few variations based on suggestions by @rafapereirabr and @pedro-andrade-inpe:

![gtfs_tools](https://user-images.githubusercontent.com/7387691/143623312-16dc36df-ddf4-438f-bc4a-49f36437f22e.jpg)

I've tried thinner borders (or no border at all), but it looks awful.

**Comment by pedro-andrade-inpe** [comment]
I like the middle one in the second line.

**Comment by dhersz** [comment]
I like the left one from the second row :>

**Comment by rafapereirabr** [comment]
I'm fine with the first 2 options in the second row. @Joaobazzo and @mvpsaraiva , what do you think ? any preferences?

**Comment by Joaobazzo** [comment]
I like the [1,2]. Nice work @mvpsaraiva !

**Comment by mvpsaraiva** [comment]
I also prefer the bottom-left.

**Comment by pedro-andrade-inpe** [comment]
The bottom-left one is fine as well.

**Comment by rafapereirabr** [comment]
Any strong opinions about the colors ?

**Comment by mvpsaraiva** [comment]
> Any strong opinions about the colors ?

The colors were inspired by the dark yellow and black [Catterpilar palette](https://www.google.com/search?q=caterpillar&hl=pt-BR&sxsrf=AOaemvJvc8QMCJ8mIetRHqOlJTjEMM3Hlg:1638190982263&source=lnms&tbm=isch&sa=X&ved=2ahUKEwje_Mj80L30AhUvrpUCHeFCDd0Q_AUoAnoECAIQBA&biw=1680&bih=839&dpr=2). They are the first colors that come to my mind when I think of tools :)

**Comment by kauebraga** [comment]
Love the colors!

**Comment by rafapereirabr** [comment]
> > Any strong opinions about the colors ?
> 
> The colors were inspired by the dark yellow and black [Catterpilar palette](https://www.google.com/search?q=caterpillar&hl=pt-BR&sxsrf=AOaemvJvc8QMCJ8mIetRHqOlJTjEMM3Hlg:1638190982263&source=lnms&tbm=isch&sa=X&ved=2ahUKEwje_Mj80L30AhUvrpUCHeFCDd0Q_AUoAnoECAIQBA&biw=1680&bih=839&dpr=2). They are the first colors that come to my mind when I think of tools :)

Ok, you convinced me here

**Comment by rafapereirabr** [comment]
I guess the [1,2] options got the most votes. @mvpsaraiva , could you please add the figure to the repo directory and close the issue? \o/

**Comment by mvpsaraiva** [comment]
Cool. I've properly aligned a few things that @dhersz noticed with his eagle eyes, and made a black version as well - maybe for use in special occasions :)

<img width="867" alt="Screenshot 2021-12-15 at 12 03 57" src="https://user-images.githubusercontent.com/7387691/146210919-6ea0542a-a97a-4ee4-8a42-f943e1fae6e4.png">
