### ISSUE TITLE
Optimizing `get_trip_speed()`

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/gtfstools#38]
`get_trip_speed()` can take some time if we're dealing with a big gtfs. The majority of the time is spent calculating the length of trips. An obvious optimization is to calculate the length of the shapes/patterns of stop times before joining them to trips. Otherwise we calculate the length of the same geometry multiple times, which is exactly what we're doing right now.

To solve this for the shapes case is pretty simple, we just need to use `convert_shapes_to_sf()`, calculate the length and then join to trips, instead of using `get_trip_geometry(file = "shapes")` and then calculating the length.

For the stop times case it's a bit less simple, because we have to identify identical patterns of stop times, and then generate only one geometry per pattern, to later join to trips. This optimization could also be implemented to `get_trip_geometry()` in the case of stop times.

**Comment by dhersz** [comment]
Looking at the profvis for a `get_trip_speed()` call that took 79s (file = "shapes" only), 19s are spent on `get_trip_geometry()`. From these, around **18s** are spent selecting/reordering the columns.

This is done twice now, first `shapes_sf <- shapes_sf[, .(trip_id, origin_file, geometry)]` (11s) and then in the end `final_sf <- final_sf[, .(trip_id, origin_file, geometry)]` (7s). Even though they're almost identical, they don't serve the same purpose. The first is  to remove some columns, and the second to reorder them. I should be using `shapes_sf[, x := NULL]` in the first case and `setcolorder()` in the second.

**Comment by rafapereirabr** [comment]
One way to make this slightly faster (and more elegant with less code) is to calculate geometry length inside a `data.table` call. Like this:

```

# starting a fresh session
library(gtfstools)
library(data.table)
library(tictoc)

### read gtfs
data_path <- system.file("extdata/spo_gtfs.zip", package = "gtfstools")
gtfs <- read_gtfs(data_path)

### get geometries
trips_geometries <- get_trip_geometry(gtfs, trip_id=NULL, file='shapes')

# let's make it 1024 times bigger
trips_geometries <- rbind(trips_geometries, trips_geometries, trips_geometries, trips_geometries)
trips_geometries <- rbind(trips_geometries, trips_geometries, trips_geometries, trips_geometries)
trips_geometries <- rbind(trips_geometries, trips_geometries, trips_geometries, trips_geometries)
trips_geometries <- rbind(trips_geometries, trips_geometries, trips_geometries, trips_geometries)
trips_geometries <- rbind(trips_geometries, trips_geometries, trips_geometries, trips_geometries)

### calculate the length of each geometry

# current method
tic()
  trips_length <- sf::st_length(trips_geometries)
  if (unit == "km/h") trips_length <- units::set_units(trips_length, "km")
  trips_length <- as.numeric(trips_length)
  
  trips_speed <- data.table::data.table(
    trip_id     = trips_geometries$trip_id,
    origin_file = trips_geometries$origin_file,
    length      = trips_length)
toc()
#>7.96 sec elapsed

# inside data.table
tic()
  data.table::setDT(trips_geometries)[, trips_length := sf::st_length(geometry)]
  trips_geometries[, trips_length := as.numeric( units::set_units(trips_length, "km")) ]
toc()
#> 7.32 sec elapsed



```

**Comment by dhersz** [comment]
Good call, much more elegant indeed. I'll be doing that when adjusting the function. 

Meanwhile, I have adjusted the bits I pointed above in `get_trip_geometry()` in https://github.com/ipeaGIT/gtfstools/commit/ad15cb8c3aab2249e6fac12404b80aead07580b3. What took almost 20s before now takes less than 1s. Not bad. Call that a low hanging fruit.

**Comment by dhersz** [comment]
https://github.com/ipeaGIT/gtfstools/commit/68c9fe62372e1104d067e75a04c8f66155e89333 introduced a new function, `get_trip_length()`. This function calculates the length of unique shapes and then joins this data to the trip ids, instead of joining first and calculating the length later. Since many trips might point to the same shape, we were doing lots of rework here.

Now `get_trip_speed()` with `file = "shapes"` takes around 15s with all Fetranspor trips' (176k~), whereas it would take around 70s previously.

Working on `file = "stop_times"` now.

**Comment by dhersz** [comment]
After a new round of smaller optimizations `get_trip_speed(file = "shapes")` takes on average 10s with Fetranspor's GTFS. `get_trip_speed(file = "stop_times")` takes around 17s. Both together takes 20s~. By far the most expensive operation now is transforming the times to seconds, and not calculating the length anymore.

Done with this issue for now.
