### ISSUE TITLE
Create a function to convert frequencies to stop_times

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/gtfstools#42]
Self-explanatory title.

By the way, can anyone think of a better name than `convert_frequencies_to_stop_times()`? I like the `verb_object()` structure, but it's obviously too verbose in this case.

**Comment by pedro-andrade-inpe** [comment]
The smallest name I could think would be `build_stop_times()` (build using frequencies).

**Comment by dhersz** [comment]
Thanks for the suggestion @pedro-andrade-inpe, and sorry for not answering before. `build_stop_times()` sounds good, but I think that it may be too easily misunderstood as a function that could be used to add arbitrary entries to stop_times, not necessarily from the frequencies table.

Meanwhile, I created the function and (temporarily?) named it `frequencies_to_stop_times()`. I'm closing the issue, but if anyone got suggestions, please feel free to chime in.
