### ISSUE TITLE
Filtering by stop_id does not really filter by stop_id

### ISSUE THREAD

**Issue by luukvdmeer** [ipeaGIT/gtfstools#43]
I know it is very clearly documented that when filtering by stop_id you are actually filtering trips that contain those stops :wink: I am just wondering why. This seems counter-intuitive to me, that you filter by stop_id but end up with many more stops in your filtered GTFS. Personally, when I filter stops I do that because I am really only interested in those stops. For the stop_times table it does not matter, since trips are still valid trips when the values in the stop_sequence column are not consecutive. Also, the first stop in a trip does not have to have a stop_sequence value of 1. The only requirement is that stop_sequence values increase along a trip, which will still be the case when stops are removed (see https://developers.google.com/transit/gtfs/reference#stop_timestxt). So I would argue the "integrity of trips as described in the stop_times table" is preserved also after removing stops from a trip.

Of course I can also think of use-cases where you actually want to filter trips through stop ids, but maybe this can instead be addressed through a boolean parameter like `preserve_trips` (which can then default to `TRUE` if it is assumed this is the most common use-case and to not make backward incompatible changes). 

When really filtering by stop_id (i.e. not filtering trips) it is useful (I think) to have a boolean `include_child_stops` parameter which, when set to `TRUE`, makes sure that child stops are included if a given stop_id refers to a parent stop (as is already happening in the current implementation). Probably `TRUE` is also the best default value for this one. But the possibility is then there to set it to `FALSE` and really keep only the stop_ids that you provide (which is in the end what you'd expect a filter function to do).

The only issue to overcome would be how to update the shapes table if present. Not sure about that yet.

Happy to contribute if needed and when you think the idea makes sense!

Relates to #44.

**Comment by dhersz** [comment]
Hi @luukvdmeer. Thank you very much for opening the issues.

As you probably guessed, I was under the (wrong) impression that no one would want to keep only a few stops of trips. I'm happily proven wrong.

I think both your suggestions are great (but I wonder if `include_child_stops` should actually be called `include_parent_stops`), and I'll start working on them in the next few days (unless you already have a PR triggered).

Correct me if I'm wrong, but the shapes table is only related to the stops via shapes -> trips -> stop_times -> stops, right? So I'd say that we keep the shapes that correspond to the trips that include the specified stops, but don't adjust the shapes themselves. What do you think?

**Comment by luukvdmeer** [comment]
> but I wonder if `include_child_stops` should actually be called `include_parent_stops`

Good point. My thought was that it can be useful that if you provide the id of a parent stop it also keeps all child stops. E.g. each platform in a a train station may be modelled as separate stop. Then, if you provide only the id of the parent station to the filter function, it will automatically keep all of its platforms, so that you don't have to provide the ids of the platforms themselves separately (but you can disable this default behaviour by setting the parameter to FALSE). Keeping only the parent stop is in most cases not so useful since no trips depart from it (they depart from any of the platforms). But indeed, the other way around also makes sense (keeping parent stops of referenced child stops). Maybe it can do both? Something like `preserve_stop_relations`, `preserve_relations` or `preserve_inheritance`? (not sure about the naming)

> Correct me if I'm wrong, but the shapes table is only related to the stops via shapes -> trips -> stop_times -> stops, right? So I'd say that we keep the shapes that correspond to the trips that include the specified stops, but don't adjust the shapes themselves. What do you think?

Yes, that is also my understanding. However, in a "perfect solution" the shape of an affected trip would be updated if the last n and/or the first n stops of a trip are removed (if only stops somewhere in the middle are removed the shape of the affected trip should indeed stay the same). But I don't think that is easy, since shapes don't even have to intersect with the stop locations themselves, so to do it good we would have to snap the remaining stops to the shape and then cut the shape at the snapped locations of respectively the first and last remaining stop. That would be quite some overhead, and not sure if that is worth it. For me it sounds good to only filter them and not adjust the shapes themselves (with a brief mention of that in the documentation).

**Comment by dhersz** [comment]
> > but I wonder if `include_child_stops` should actually be called `include_parent_stops`
> 
> Good point. My thought was that it can be useful that if you provide the id of a parent stop it also keeps all child stops. E.g. each platform in a a train station may be modelled as separate stop. Then, if you provide only the id of the parent station to the filter function, it will automatically keep all of its platforms, so that you don't have to provide the ids of the platforms themselves separately (but you can disable this default behaviour by setting the parameter to FALSE). Keeping only the parent stop is in most cases not so useful since no trips depart from it (they depart from any of the platforms). But indeed, the other way around also makes sense (keeping parent stops of referenced child stops). Maybe it can do both? Something like `preserve_stop_relations`, `preserve_relations` or `preserve_inheritance`? (not sure about the naming)

Ok, I totally forgot stops could also have childs, and not only parents haha

In such case, I think we could use two different arguments, something along the lines of `include_parent` and `include_children`. These arguments would default to `TRUE`, which means including parents and children in the filter. `FALSE` would exclude them. And they could also take a character string, so we include only the parent/children of specified stops (e.g. `filter_by_stop_id(gtfs, stop_id, include_parent = c("a_stop", "b_stop"), include_children = TRUE)` would keep all stops specified in `stop_id`, the parents of "a_stop" and "b_stop" and the children of all stops specified in `stop_id`.

It seems to me a good way to handle these cases, what do you think?

> 
> > Correct me if I'm wrong, but the shapes table is only related to the stops via shapes -> trips -> stop_times -> stops, right? So I'd say that we keep the shapes that correspond to the trips that include the specified stops, but don't adjust the shapes themselves. What do you think?
> 
> Yes, that is also my understanding. However, in a "perfect solution" the shape of an affected trip would be updated if the last n and/or the first n stops of a trip are removed (if only stops somewhere in the middle are removed the shape of the affected trip should indeed stay the same). But I don't think that is easy, since shapes don't even have to intersect with the stop locations themselves, so to do it good we would have to snap the remaining stops to the shape and then cut the shape at the snapped locations of respectively the first and last remaining stop. That would be quite some overhead, and not sure if that is worth it. For me it sounds good to only filter them and not adjust the shapes themselves (with a brief mention of that in the documentation).

Yeah, I see how that would be the perfect solution (very related to #44 indeed). The hard part here is definitely the snapping function. Once we have that implemented, I think the user could control whether to adjust the shapes with a `trim_shapes` argument, which would perhaps default to `FALSE` (not sure though).

**Comment by dhersz** [comment]
This issue has finally been tackled in https://github.com/ipeaGIT/gtfstools/commit/5d3b954115b70497176880044c49fcba2813ece4 and a few previous commits.

The behavior of filtering by trips that contain the specified stops has been deprecated. For backwards compatibility reasons, however, this behavior will still be the default for the next release (v1.3.0) and is controlled by the parameter `full_trips`.

To actually filter by `stop_id`s (the behavior that I agree is the most appropriate), please use `full_trips = FALSE`. This behavior will be the default from version 2.0.0 onward. To achieve the current behavior in a most "explicit" way, manually subset the stop_times table by `stop_id` and specify the `trip_id`s included in the output in `filter_by_trip_id()`.  When using `full_trips = TRUE` the function call will always throw a warning, since the "fix" for it is easy.

The function now also takes the parameters `include_children` and `include_parents`, which defaults to `TRUE`.

**Comment by dhersz** [comment]
I will close this issue in favor of a new one that addresses the deprecation more explicitly.
