### ISSUE TITLE
Filtering fares by zone id

### ISSUE THREAD

**Issue by luukvdmeer** [ipeaGIT/gtfstools#45]
Currently the fare tables are filtered in two ways (please correct me if I am wrong!):

- The `fare_attributes` table may have an `agency_id` column. All rows with non-relevant agencies can be removed, and the remaining fare_ids can be used to filter the `fare_rules` table.
- The `fare_rules` table may have a `route_id` column. All rows with non-relevant routes can be removed, and the remaining fare_ids can be used to filter the `fare_attributes` table.

However, fare rules can also be based on fare zones rather than on routes. Especially in cities this happens quite often. In that case they have a zone index stored in either the `origin_id`, `destination_id` or `contains_id` columns. This zone indices refer to values in the `zone_id` column in the stops table. Hence, when stops are removed (e.g. by filtering trips) some zones might not be present anymore, and the `fare_rules` table can be filtered to only contain relevant zones. The remaining fare_ids can then be used to filter the `fare_attributes` table.

See https://developers.google.com/transit/gtfs/reference#fare_rulestxt for reference

Again, please correct me if I made wrong assumptions!

**Comment by dhersz** [comment]
Done in https://github.com/ipeaGIT/gtfstools/commit/0ac3d1c3035f2df68b0cabfddadbf34b4de2f520. Sorry for taking so long to tackle this issue. Please let me know if you find any problems.
