### ISSUE TITLE
Converting bbox to polygon

### ISSUE THREAD

**Issue by luukvdmeer** [ipeaGIT/gtfstools#47]
Sorry for the issue overload. I just saw the internal function `polygon_to_bbox`. Just wanted to mention that you can directly convert a bbox object to an sfc object (with POLYGON geometry) using `sf::st_as_sfc(bbox)`. If the bbox has a CRS attached this will be copied to the sfc object.

**Comment by dhersz** [comment]
No worries about the issue overload. I'm happy that you're using the package and finding inconsistencies/problems.

Thank you for letting me know about `sf::st_as_sfc(bbox)`. Fixed in https://github.com/ipeaGIT/gtfstools/commit/b3e11d9431251d85350313187dc99e7de704ad6d.

**Comment by dhersz** [comment]
By the way, perhaps you know a proper answer to this:

Sometimes, a polygon created by a bbox doesn't "contain" the sf used to create the bbox. For example:

``` r
library(gtfstools)
library(sf)
#> Linking to GEOS 3.9.1, GDAL 3.3.2, PROJ 7.2.1
library(ggplot2)

data_path <- system.file("extdata/spo_gtfs.zip", package = "gtfstools")
gtfs <- read_gtfs(data_path)

shape_id <- "68962"
shape_sf <- convert_shapes_to_sf(gtfs, shape_id)
bbox <- sf::st_bbox(shape_sf)

sf::st_contains(sf::st_as_sfc(bbox), shape_sf, sparse = FALSE)
#>       [,1]
#> [1,] FALSE

ggplot() + geom_sf(data = sf::st_as_sfc(bbox)) + geom_sf(data = shape_sf)
```

![](https://i.imgur.com/EDWzGuz.png)

So in order to overcome this "issue", I create a 0 dist buffer around the bbox polygon:

``` r
sf::st_contains(
  sf::st_buffer(sf::st_as_sfc(bbox), 0),
  shape_sf, sparse = FALSE
)
#>      [,1]
#> [1,] TRUE
```

That seems fine, but if I plot this buffered geometry, it has this weird borders. 

```r
ggplot() +
  geom_sf(data = sf::st_buffer(sf::st_as_sfc(bbox), 0)) +
  geom_sf(data = shape_sf)
```

![](https://i.imgur.com/f0roXHc.png)

Which I guess may be related to the "snapping" of the edges to the coordinate system, or something like that, but I'm really not sure. Am I doing something wrong here/is there a better way to handle these cases?

**Comment by luukvdmeer** [comment]
No, I am not sure. I just know that things have changed after `sf` started using `s2` for spherical geometric operations when coordinates are lat/lon. You will see that when you switch off `s2` by running `sf_use_s2(FALSE)` the buffer looks good (and the box even contains the linestring already before buffering), but I would not dare to say that is the recommended way, since it means using cartesian geometry with lat/lon coordinates :laughing: Not sure what the reasons are though, opening an issue in `sf` might be the best way to find out

As far as I understand the clean way for handling the failure of contains would be to set the precision of the objects before calling the predicate. This prevents errors regarding floating-point precision (see e.g. https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f).  A sensible value for precision would for example be `1e08`, instead of the default of 0, which means no rounding is done at all (see https://github.com/r-spatial/sf/pull/1482). But I tested it and it does not help. Precision is normally forwarded to GEOS whenever a GEOS function is called, but not sure if s2 also understands it (apparently not?).

```r
box = st_as_sfc(bbox)
st_precision(box) = 1e8
st_precision(sf_shape) = 1e8
st_contains(box, sf_shape)

#       [,1]
# [1,] FALSE
```

**Comment by dhersz** [comment]
Thanks for taking a look into this! I think I'll open an issue in `sf` then, to see if there's a proper/recommended way of dealing with this in a package.
