### ISSUE TITLE
Retaining only specified stops.

### ISSUE THREAD

**Issue by LeonLeprau** [ipeaGIT/gtfstools#51]
Hi there ,

So I just wanted to say thanks for the last advice, I was able to get all my specified stops into a vector.

I run the filter and as someone has mentioned before, the tool keeps all my specified stops and stops associated with routes that pass through my specified stops. this means my resulting gtfs data has about 8000 stops instead of my original 4000

I was wondering if there is a way to just retain the specified stop id's and their associated data?

Thanks so much for your help, this tool is really useful.

All the best,
Leon

**Comment by dhersz** [comment]
Unfortunately there's no way to do so right now. I'll be working on a new version of `filter_by_stop_id()` in the next couple weeks, which will probably figure in the next release or the subsequent one.

I'll close this issue in favor of the older one. If you have anything else to add please do so there. Cheers.
