### ISSUE TITLE
behavior of filter_by_sf with sf::st_crop

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfstools#58]
I have the impression that the `filter_by_sf()` might not be working as it is supposed to when one sets `spatial_operation = sf::st_crop`. See the reprex below, where my aim was to keep only the parts of the shapes within the buffer.

```
library(gtfstools)
library(ggplot2)
library(units)

# read GTFS
path <- system.file("extdata/spo_gtfs.zip", package = "gtfstools")
gtfs <- gtfstools::read_gtfs(path)


# before cut -------------------------------------------------------------
shapes <- gtfstools::convert_shapes_to_sf(gtfs)
stops <- gtfstools::convert_stops_to_sf(gtfs)
center <- subset(stops, stop_id == 18870)


# buffer
buff <- sf::st_buffer(x = center, 
                      dist = 0.07 )

# plot
ggplot() +
  geom_sf(data=buff, fill='gray', alpha=.3) +
  geom_sf(data=shapes, color='green') + 
  geom_sf(data=center, color='red') 
```
![Rplot0](https://user-images.githubusercontent.com/7448421/173965451-4cabe391-9357-40fb-8ebb-fa969259da2e.png)

```
# after cut -------------------------------------------------------------

# sf_use_s2(FALSE)
gtfs_cut <- gtfstools::filter_by_sf(gtfs = gtfs,
                                    geom = buff,
                                    spatial_operation = sf::st_crop)

shapes_cut <- gtfstools::convert_shapes_to_sf(gtfs_cut)

ggplot() +
  geom_sf(data=buff, fill='gray', alpha=.3) +
  geom_sf(data=shapes_cut, color='green') + 
  geom_sf(data=center, color='red') 
```
![Rplot1](https://user-images.githubusercontent.com/7448421/173965462-a6af374e-6230-4013-a8ee-a565ac99bdbc.png)

**Comment by dhersz** [comment]
Hi Rafa. As the function documentation says, you have to use one of the functions from [this list](https://r-spatial.github.io/sf/reference/geos_binary_pred.html). It probably won't work with any other function.

I'll add an assertion to make sure only valid functions are accepted.

**Comment by dhersz** [comment]
Fixed in https://github.com/ipeaGIT/gtfstools/commit/935468e16595d6c03d61efe69e19b553c5722503.
