### ISSUE TITLE
error in `set_trip_speed()`

### ISSUE THREAD

**Issue by alenastern** [ipeaGIT/gtfstools#63]
Hello! I believe I've encountered a bug in the `set_trip_speed()` function. I am trying to use the function to modify bus trip speeds for WMATA ([transitland feed entry](https://www.transit.land/feeds/f-dqc-wmata~bus))

I've included a reproducible example below (requires downloading the latest file at the link above).
```
gtfs_bus <- read_gtfs(here("data/raw-data", "wmata_bus_latest.gtfs.zip"))
gtfs_route <- filter_by_route_id(gtfs, c("52", "54", "59"))
trip_ids <- gtfs_route$trips$trip_id
speed_factor_km <- 20
gtfs_route_new <- set_trip_speed(gtfs = gtfs_route,
                                     trip_id = trip_ids,
                                     speed = speed_factor_km,
                                     unit = "km/h")
trip_speeds_new <- get_trip_speed(gtfs_route_new, unit = "km/h")
```

When I run this code, all of the values in the `speed` column in `trip_speeds_new` are `Inf`. Upon inspecting the [source code](https://github.com/ipeaGIT/gtfstools/blob/master/R/set_trip_speed.R) for `set_trip_speed()` I think the issue is caused by how the function identifies the indices for the last stop in the trips to be modified. The code assumes sequential values of `stop_sequence` such that the maximum value of `stop_sequence` is also the appropriate index within each group. In my case, the route I was inspecting had 50 stops but the maximum stop sequence value was 59 (there were some skipped numbers in the sequence). As a result, the current code below returned a `max_stops_index` value of `NA_integer_`. The suggested modification gives the index of the largest `stop_sequence` value, but doesn't assume they're the same. When I ran this, it returned the right result for my data.

```
# Current code
if (identical(trip_length_ids, character(0))) {
    max_stops_index <- 0
  } else {
    max_stops_index <- stop_times[
      trip_id %chin% trip_length_ids,
      .I[max(stop_sequence)],
      by = trip_id
    ]
    max_stops_index <- max_stops_index$V1
  }

# Suggested modification 
if (identical(trip_length_ids, character(0))) {
    max_stops_index <- 0
  } else {
    max_stops_index <- stop_times[
      trip_id %chin% trip_length_ids,
     .I[which(stop_sequence == max(stop_sequence))],
      by = trip_id
    ]
    max_stops_index <- max_stops_index$V1
  }
```

Please let me know if you have any questions and thanks so much for your help!

**Comment by dhersz** [comment]
Hi @alenastern, thank you very much for opening the issue.

I have adjusted the code as you suggested. I just omitted the `which()` call, because data.tables can take logical vectors to subset data, so we don't need to "convert" a logical vector to an index with `which()`.

Please give the current dev version a try to check if it fixes your issue and please let me know if there's anything else that should be adjusted. Cheers!

**Comment by alenastern** [comment]
Thank you so much for the quick reply and fix! I'm excited to give the current dev version a try and will report back!

**Comment by alenastern** [comment]
@dhersz thanks again for the quick bug fix! I tested out the current dev version and the fix seems to have resolved the original issue, though I'm still not getting the results I'd expect. For `trip_id = 10017020` in the dataset I shared in the original issue, the  start time is 18:45:00 and the `trip_duration` calculated within `set_trip_speed` with a desired speed of 20 km/h is 0.509 hours, so I'd expect the updated arrival time for the last stop to be about 19:15:54, but the function returns 19:05:17 as the arrival time for the last stop. This then yields an average speed of 30.11 km/h when I run `get_trip_speed` on the modified gtfs object - much faster than my desired sped of 20 km/h!

I think the issue may be with the `cpp_time_to_seconds` function [here](https://github.com/ipeaGIT/gtfstools/blob/master/R/cpp11.R) but I'm not able to understand what's going on from the code on github. Do you have any thoughts on what might be causing the issue?

Please let me know if I can pass along any information and thanks again for your help!

**Comment by dhersz** [comment]
Hi @alenastern. I just tested with the dataset you provided and I'm getting the last stop as 19:15:32 (which seems to be correct, given the duration of 0.509 hours). Here's my code:

``` r
library(gtfstools)

gtfs <- read_gtfs("/tmp/gtfs.zip")

gtfs <- filter_by_trip_id(gtfs, "10017020")

new_speed_gtfs <- set_trip_speed(gtfs, "10017020", 20)

new_speed_gtfs$stop_times

get_trip_speed(new_speed_gtfs, "10017020")
#>     trip_id origin_file   speed
#> 1: 10017020      shapes 20.0056
```

<sup>Created on 2022-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by alenastern** [comment]
@dhersz - thanks again for the quick response and apologies for the bit of misdirection. I wasn't able to exactly replicate the result I shared, but in examining that further I think I landed on the cause of the odd results - due to the different behavior of `set_trip_speed` when the `trip_id` parameter is a single id vs a vector of ids. You can see below that when I pass a vector of trip ids to `set_trip_speed` my results are not only different than when run on a single trip id, but in a good number of cases I get resulting speeds very different from 20. My interpretation of the function documentation is that it should accept a vector of trip_ids, but please let me know if that isn't supported input. It would be very helpful to be able to modify the speed for multiple trip ids at once to model the impact of a route-level change (as I was trying to do in the reprex below).

Thanks again so much for your help!

``` r
library(gtfstools)
library(here)
library(tidyverse)

gtfs <- read_gtfs(here("data/raw-data", "wmata_bus_latest.gtfs.zip"))
route_id <- c("52", "54", "59")

gtfs_route <- filter_by_route_id(gtfs, route_id)
trip_ids <- gtfs_route$trips$trip_id
gtfs_route_new <- set_trip_speed(gtfs = gtfs_route,
                                 trip_id = trip_ids,
                                 speed = 20,
                                 unit = "km/h")

gtfs_route_new$stop_times %>%
  filter(trip_id == "10017020") %>%
  slice_tail()
#>     trip_id arrival_time departure_time stop_id stop_sequence stop_headsign
#> 1: 10017020     19:17:39       19:17:39   27665            47              
#>    pickup_type drop_off_type shape_dist_traveled timepoint
#> 1:           0             0                  NA         1
trip_speeds <- get_trip_speed(gtfs_route_new)

get_trip_speed(gtfs_route_new, "10017020")
#>     trip_id origin_file    speed
#> 1: 10017020      shapes 18.70866
get_trip_speed(gtfs_route_new, "10142080")
#>     trip_id origin_file   speed
#> 1: 10142080      shapes 14.4554
new_speed_gtfs <- set_trip_speed(gtfs, "10017020", 20)
get_trip_speed(new_speed_gtfs, "10017020")
#>     trip_id origin_file   speed
#> 1: 10017020      shapes 20.0056
new_speed_gtfs <- set_trip_speed(gtfs, "10142080", 20)
get_trip_speed(new_speed_gtfs, "10142080")
#>     trip_id origin_file    speed
#> 1: 10142080      shapes 20.00906
max(trip_speeds$speed)
#> [1] 103.6971
min(trip_speeds$speed)
#> [1] 3.942346
trip_speeds %>% filter(speed < 15 | speed > 25) %>% nrow()
#> [1] 253
```

<sup>Created on 2022-08-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dhersz** [comment]
Do you mind sending the GTFS data to my email, please (you can check it on the package DESCRIPTION file)?

I downloaded it to a temporary location yesterday and now I'm not being able to download it neither from Trasitland nor from WMATA developer website :(

I tried replicating the issue on another GTFS but wasn't able to, unfortunately.

**Comment by alenastern** [comment]
@dhersz - just sent the email! Thank you!

**Comment by dhersz** [comment]
It should now be fixed for good. The problem was that some trip_ids appeared in different orders in trips and stop_times. So the duration of trips was in one order and their departure time was in another. When I summed them to get the new arrival time I was ignoring that, so I was, for example, summing the departure time of trip 1 with the duration of trip 2. Which is why you probably couldn't replicate the situation that lead to the first value you posted (because you were using a specific combination of trip_ids, I'd guess) and why I wasn't able to replicate it with one of my test feeds. I should probably write a test for this in the near future hehe

The code below shows that all speeds are now correctly being updated (with some minor rounding errors):

``` r
library(gtfstools)

gtfs <- read_gtfs("/tmp/wmata_bus_latest.gtfs.zip")
route_id <- c("52", "54", "59")

gtfs_route <- filter_by_route_id(gtfs, route_id)
trip_ids <- gtfs_route$trips$trip_id
gtfs_route_new <- set_trip_speed(
  gtfs_route,
  trip_ids,
  speed = 20
)

speeds <- get_trip_speed(gtfs_route_new)
summary(speeds$speed)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   20.00   20.01   20.01   20.01   20.01   20.01

gtfs_route_new$stop_times[trip_id == "10017020"][c(1, 40)]
#>     trip_id arrival_time departure_time stop_id stop_sequence stop_headsign
#> 1: 10017020     18:45:00       18:45:00    8676             2              
#> 2: 10017020     19:15:32       19:15:32   27665            47              
#>    pickup_type drop_off_type shape_dist_traveled timepoint
#> 1:           0             0                  NA         1
#> 2:           0             0                  NA         1
```

<sup>Created on 2022-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Please install the dev version and check if the problem was fixed on your side as well, and please report any issues you might face. Cheers!

**Comment by alenastern** [comment]
Amazing @dhersz - I just installed the dev version and the problem seems to be fixed on my side! Thank you again so much for all your help!

**Comment by dhersz** [comment]
Cool, thank you for reporting the bugs.
