### ISSUE TITLE
Extraction by route_type for extended route types

### ISSUE THREAD

**Issue by Ge-Rag** [ipeaGIT/gtfstools#70]
Great tool for filtering gtfs feeds to one's needs. 

I am doing extracts by route_type and came across the problem, that it cannot deal with extended route_types:

https://developers.google.com/transit/gtfs/reference/extended-route-types

Extended route types are now used in most European feeds, so to extract them by route_type I have to convert to standard route types first, which is an ugly solution.

Is there any chance this will be adopted in the near future?

**Comment by dhersz** [comment]
Thanks for opening the issue.

https://github.com/ipeaGIT/gtfstools/commit/28003935e3339f75ee4f52dde6b43dfb1704a5b9 should allow extended route types. Please let me know if you face any problems with it.

**Comment by Ge-Rag** [comment]
Thank you for the quick update!

However we are not there quite yet.

Sorry I didn't mention this before but there are feeds that have std and extended route types:

The Denmark feed:

https://data.public-transport.earth/gtfs/dk

Has overlapping route_types (std and extended mixed)

This is a grouped output of routes.txt

rType  count
    0      3
    1      4
    2     30
    3   1564
    4     14
  109      7
  700      8
  715     78

The current version will not dynamically deal with that. 

It would be much more convenient if the std  rtype numbers could be used to cover also the extended ones. I.e. filtering by std route type 2 would also take care of  extended types from 100:117.

filter_by_route_type(spo_gtfs, route_type = 2, keep = TRUE) would also cover 100:117. 

Viceversa this would not work as there is not a std rt for each extended one, but this would not really be needed.

Another issue that came up is the fact that feed_into.txt was changed so the dates now look like YYYY-MM-DD instead of YYYYMMDD, as defined by google.

This issue came up when I wanted to start pfaedle to generate shapes from OSM maps.

https://github.com/ad-freiburg/pfaedle

**Comment by dhersz** [comment]
I'd prefer keeping the function behaving like it is nowadays. Using your very example, how would one be able to keep route_type 2 and not 109, if setting `route_type = "2"` included types from 100 to 117? I don't think calling `filter_by_route_type(gtfs, route_type = as.character(100:117))` is that much inconvenient as well, to be honest.

I don't understand the feed_info issue. You mean that after writing the feed with `write_gtfs()` the date format looks like YYYY-MM-DD or that it looks like this when you're inspecting the GTFS object in R? The second case is expected, as dates are converted from character to Date objects, so they're easier to manipulate.

**Comment by Ge-Rag** [comment]
I understand your concerns and there is no real good solution for the problem. Maybe a more viable solution would be to use keywords to categorize route_types. Extended route types are becoming reality. 
In the above mentioned pfaedle this issue was solved in that way.

From the help:
 -m [ --mots ] arg (=all)         MOTs to calculate shapes for, comma sep.,
                                     either as string {all, tram | streetcar,
                                     subway | metro, rail | train, bus,
                                     ferry | boat | ship, cablecar, gondola,
                                     funicular, coach, mono-rail | monorail,
                                     trolley | trolleybus | trolley-bus} or
                                     as GTFS mot codes

So by using -m rail it will deal with std code 2 and 100:117.

Concerning the date issue, yes the date format changes after `write_gtfs()`. I discovered this only because I ran pfaedle on the newly created feed to generate shapes and it complained about the date format.

**Comment by dhersz** [comment]
Thanks for the suggestions @Ge-Rag.

I'll still have to put some thought into it before making any change, and I must admit that this is low priority for now, but I'll keep an eye open on possible alternatives. By the way, do you know why in pfaedle documentation some transport modes are separated by commas and other by vertical bars? (e.g. "all, tram | streetcar, subway | metro, rail | ...")

Regarding `feed_info` date fields, you're correct, they were not being converted back to their original format. My bad. This was fixed in https://github.com/ipeaGIT/gtfstools/commit/395ad540858dd05bab54a45e91c958800bc3f66e.

**Comment by Ge-Rag** [comment]
Okay thanks for correcting the date issue. Concerning the `pfaedle` docu the | acually means 'or' so you can either enter metro or subway , both have the same meaning.
