### ISSUE TITLE
Error when using get_trip_geometry() and get_trip_speed(): sfheaders - error indexing lines

### ISSUE THREAD

**Issue by nadiaqamilla** [ipeaGIT/gtfstools#72]
Hi, thanks a lot for the powerful package. I'm trying to use the package on Transjakarta's GTFS data (BRT in Jakarta, the capital of Indonesia), available here https://ppid.transjakarta.co.id/pusat-data/data-terbuka

1. I tried getting all geometries with get_trip_geometry() using the 'shapes' file. However, as I run the code, it always resulted in an error --> **Error: sfheaders - error indexing lines, perhaps caused by un-ordered data?**
However, it would work if I defined some of the trip_id in the code. It would also work if I use the 'stop_times' file to generate all geometries, but it is not the realistic geometry that I preferred as it consists of straight lines.

2. Retrieving all trip speeds with get_trip_speed() using 'shapes' file also yielded the same error above (error indexing lines)
<img width="500" alt="image" src="https://github.com/ipeaGIT/gtfstools/assets/140500332/d503249e-3a8f-4fe6-b47d-61e7da56b7bc">

3. Could anyone give me an example code if I want to filter the trip_headsign from the trips table that contains some specific words? I tried using the filter_by_() function gtfstools and filter function from the dpylr however I haven't found the right code to run it.

**Comment by nadiaqamilla** [comment]
Hi @dhersz, thank you for the solutions. I've installed the dev version and it works now. Kindly inform if it's ready for get_trip_speed().

**Comment by dhersz** [comment]
`get_trip_speed()` now includes `sort_sequence` as well, as of https://github.com/ipeaGIT/gtfstools/commit/3d7b8ceb190a9e7b812f0b61c4fe285a67819be6.

**Comment by baarthur** [comment]
guys, same error in a different function: `filter_by_spatial_extent`. perhaps sort_sequence could be passed on earlier, e.g. at read_gtfs? or simply duplicate the ordering pipeline to the other function as well.
