### ISSUE TITLE
function copy_gtfs_without_field

### ISSUE THREAD

**Issue by Ge-Rag** [ipeaGIT/gtfstools#74]
According to the gtfstools documentation at:

https://www.rdocumentation.org/packages/gtfstools/versions/1.2.0/topics/copy_gtfs_without_field

There is a function called: copy_gtfs_without_field()

However when I list the package contents of gtfstools, this function and other copy functions don't show up. Not even in the development version.

Have these functions been removed, or is the documentation at the above link simply useless?

I'm asking because these two functions would come in handy to remove fields containing shape data from some providers that are simply useless. (just straight lines). 

regards,
George

**Comment by dhersz** [comment]
The `copy_*()` functions are all internal, so you have to use the special operator `:::` to use them - e.g. `gtfstools:::copy_gtfs_without_field()`.

I have honestly never thought they would be of interest of a wider audience. I'll think about exporting them.
